spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    mongodb:
      uri: mongodb://megetood-bucks:megetood-bucks@localhost:27017/mbucks
  redis:
    host: localhost
    lettuce:
      pool:
        max-active: 5
        max-idle: 5
  cache:
    cache-names: coffee
    type: redis
    redis:
      time-to-live: 5000
      cache-null-values: false
#  datasource:
#    url: jdbc:p6spy:h2:men:testdb
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    username: sa
#    password:

mybatis:
  type-handlers-package: com.megetood.bucks.hander
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  offset-as-page-num: true
  reasonable: true
  page-size-zero: true
  support-methods-arguments: true

# 自定义 redis 配置
redis:
  host: localhost
  max-total: 5
  max-idle: 5
  test-on-borrow: true

# 此两种皆可
#  maxTotal: 5
#  maxIde: 5
#  testOnBorrow: true