spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    host: localhost
    lettuce:
      pool:
        max-active: 5
        max-idle: 5
  cache:
    cache-names: coffee
    type: redis
    redis:
      time-to-live: 5000
      cache-null-values: false

# 自定义 redis 配置
redis:
  host: localhost
  max-total: 5
  max-idle: 5
  test-on-borrow: true

# 此两种皆可
#  maxTotal: 5
#  maxIde: 5
#  testOnBorrow: true